[project]
name = "hacker-dojo-python-group"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.8.0",
]

[tool.uv.workspace]
members = [
    "BART-Caltrain-map",
    "bart-vibe",
    "PatternMatching",
]
