[project]
name = "flaskfastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.2",
    "fastapi>=0.115.12",
    "flask>=3.1.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
